#ifndef NEXA_TOTEM_ESP8266_CONFIG_EXAMPLE_H
#define NEXA_TOTEM_ESP8266_CONFIG_EXAMPLE_H

#define NEXA_WIFI_SSID "NeXa-ToTem"
#define NEXA_WIFI_PASSWORD "nexa12345"
#define NEXA_PI_SERVER_URL "http://10.42.0.1:8080/api/hardware"

#endif
