#ifndef NEXA_TOTEM_ESP8266_CONFIG_EXAMPLE_H
#define NEXA_TOTEM_ESP8266_CONFIG_EXAMPLE_H

#define NEXA_WIFI_SSID "NeXa-ESP"
#define NEXA_WIFI_PASSWORD "nexa12345"
#define NEXA_ESP_IP "192.168.4.1"
#define NEXA_ESP_STATE_PATH "/api/state"
#define NEXA_ESP_STATE_URL "http://192.168.4.1/api/state"

#endif
